//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TasksManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class konfigurime
    {
        public int nrrendor { get; set; }
        public string emertimi { get; set; }
        public Nullable<int> vlera { get; set; }
    }
}
